#create user
POST http://localhost:4000/users/register
Content-type: application/json

{
  "username": "testi",
  "firstName": "Joku",
  "lastName": "Vaan",
  "password": "kokeilu"
}

###

#get all users
GET http://localhost:4000/users
